version: '3'
services:
  peer1:
    build: .
    volumes:
      - ./:/go/src/github.com/golang-blockchain
    command: ["go", "run", "main.go", "-l", "10000", "-g", "golangblockchain_mongo1_1"]
  mongo1:
    image: "mongo:latest"
  mongo2:
    image: "mongo:latest"
  peer2:
    image: "golangblockchain_peer1:latest"
    volumes:
      - ./:/go/src/github.com/golang-blockchain
    environment:
      - PEER=golangblockchain_peer1_1
      - MONGO=golangblockchain_mongo1_2
    command: ["./run_other_peer.sh"]
